### ISSUE TITLE
Strange side effect of calling  Observable.get_measurements()

### ISSUE THREAD

**Issue by bednya** [flav-io/flavio#89]
Hi @DavidMStraub,
I was trying to play with handy getMeasurements(), but encountered a very strange side effect:

The code:
```python
import flavio
print('Flavio version:', flavio.__version__)
print('SM_prediction before get_measurements()', flavio.sm_prediction('BR(Bs->mumu)'))
print('Measurements:', flavio.Observable('BR(Bs->mumu)').get_measurements())
print('SM_prediction after get_measurements()', flavio.sm_prediction('BR(Bs->mumu)'))
```
produces the following error on the second call to sm_predictions():

```
Flavio version: 1.5.0
SM_prediction before get_measurements() 3.66775536885e-09
Measurements: ['CMS Bs->mumu 2013', 'LHCb Bs->mumu 2017', 'ATLAS Bs->mumu 2018', 'inofficial combination Bs->mumu 2019']
Traceback (most recent call last):
  File "bug_get_measurements.py", line 5, in <module>
    print('SM_prediction after get_measurements()', flavio.sm_prediction('BR(Bs->mumu)'))
  File "~/.local/lib/python3.6/site-packages/flavio/functions.py", line 40, in sm_prediction
    return obs.prediction_central(flavio.default_parameters, wc_sm, *args, **kwargs)
  File "~/.local/lib/python3.6/site-packages/flavio/classes.py", line 559, in prediction_central
    return self.prediction.get_central(constraints_obj, wc_obj, *args, **kwargs)
AttributeError: 'NoneType' object has no attribute 'get_central'
```

Am I doing something wrong?

All the best,
 Alexander

**Comment by DavidMStraub** [comment]
Hi,

I think it's just a typo. It should be:

```python
flavio.Observable['BR(Bs->mumu)'].get_measurements()
```

By using round brackets, you are effectively creating a new observable that is called `'BR(Bs->mumu)'`, for which there are apparently measurements, but for which no prediction function is defined yet.

**Comment by bednya** [comment]
Thanks, David!

My fault:( Indeed, square brackets solve the issue:)
